// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assignment.Data.Models;

public partial class Order
{
    public Guid Id { get; set; }

    public float TotalAmount { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<OrderCourse> OrderCourses { get; set; } = new List<OrderCourse>();
}