// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assignment.Data.Models;

public partial class OrderCourse
{
    public Guid Id { get; set; }

    public Guid CourseId { get; set; }

    public Guid OrderId { get; set; }

    public int Discount { get; set; }

    public float Price { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual Order Order { get; set; }
}