// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assignment.Data.Models;

public partial class ScheduleLesson
{
    public Guid Id { get; set; }

    public Guid ScheduleId { get; set; }

    public Guid LessonsId { get; set; }

    public int SlotIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Lesson Lessons { get; set; }

    public virtual Schedule Schedule { get; set; }
}